### ISSUE TITLE
--bias-tee 

### ISSUE THREAD

**Issue by bigalnz** [bigalnz/test_fft#14]
When capturing to a file with or without -bias-tee an error is thrown:

`
(.venv) PS C:\Users\AlGrant\test_pyrtlsdr\src\kiwitracker> kiwitracker -o ct_v2.npy -c 65536 -s 1048000 --carrier 160707580 -g 22.9 -m 4096000
Found Rafael Micro R820T/2 tuner
sdr.sample_rate=1024000.0, sdr.center_freq=160271000, sdr.gain=7.7
self.gain_values_db=[0.0, 0.9, 1.4, 2.7, 3.7, 7.7, 8.7, 12.5, 14.4, 15.7, 16.6, 19.7, 20.7, 22.9, 25.4, 28.0, 29.7, 32.8, 33.8, 36.4, 37.2, 38.6, 40.2, 42.1, 43.4, 43.9, 44.5, 48.0, 49.6]
Allocating 15 (non-zero-copy) user-space buffers
_samples.size=65536
<LIBUSB_ERROR_NOT_FOUND (-5): Entity not found> "Could not read 131072 bytes"
fixme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AlGrant\test_pyrtlsdr\.venv\Scripts\kiwitracker.exe\__main__.py", line 7, in <module>
  File "C:\Users\AlGrant\test_pyrtlsdr\src\kiwitracker\sample_reader.py", line 477, in main
    asyncio.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\AlGrant\test_pyrtlsdr\src\kiwitracker\sample_reader.py", line 499, in run_readonly
    async with reader:
  File "C:\Users\AlGrant\test_pyrtlsdr\src\kiwitracker\sample_reader.py", line 263, in __aexit__
    await self.aclose()
  File "C:\Users\AlGrant\test_pyrtlsdr\src\kiwitracker\sample_reader.py", line 243, in aclose
    self._close()
  File "C:\Users\AlGrant\test_pyrtlsdr\src\kiwitracker\sample_reader.py", line 230, in _close
    sdr.set_bias_tee(False)
  File "c:\Users\AlGrant\test_pyrtlsdr\.venv\Lib\site-packages\rtlsdr\rtlsdr.py", line 406, in set_bias_tee
    result = librtlsdr.rtlsdr_set_bias_tee(self.dev_p, int(enabled))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000030
`
This is the error for : `kiwitracker -o ct_v2.npy -c 65536 -s 1048000 --carrier 160707580 -g 22.9 -m 4096000` (no bias tee connected)

The error with bias tee hardware connected is the same `kiwitracker -o ct_v2.npy -c 65536 -s 1048000 --carrier 160707580 -g 22.9 -m 4096000 --bias-tee`

**Comment by bigalnz** [comment]
Perhaps bias-tee can only be set to False if enabled?
Need to update ln225-231 def _close(self):

```
    def _close(self):
        sdr = self.sdr
        if sdr is None:
            return
        self.sdr = None
        sdr.set_bias_tee(False)
        sdr.close()
```

**Comment by bigalnz** [comment]
Suggested check if bias tee is in use when closing SDR

```
    def _close(self):
        sdr = self.sdr
        if sdr is None:
            return
        self.sdr = None
        if self.sample_config.bias_tee_enable:
            sdr.set_bias_tee(False)
        sdr.close()
        ```

**Comment by bigalnz** [comment]
Feature added
